"""initial schema

Revision ID: 2f4b3fcee6e0
Revises: 
Create Date: 2026-09-04 14:01:39.247133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4b3fcee6e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_type', sa.Enum('system', 'user', 'reviewer', name='auditactorenum', native_enum=False), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('business_entity',
    sa.Column('ubid_code', sa.String(length=50), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'dormant', 'closed', 'unknown', name='entitystatusenum', native_enum=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('pan')
    )
    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_entity_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_entity_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_entity_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_entity_ubid_code'), ['ubid_code'], unique=True)

    op.create_table('source_system',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_system_code'), ['code'], unique=True)

    op.create_table('activity_event',
    sa.Column('business_entity_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('gst_filed', 'license_renewed', 'inspection', 'power_usage', 'employee_filing', 'payment_received', 'complaint', 'document_update', 'zero_power_usage', 'suspension_notice', 'closure_notice', 'license_cancelled', name='eventtypeenum', native_enum=False), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_event_business_entity_id'), ['business_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_event_event_type'), ['event_type'], unique=False)

    op.create_table('source_record',
    sa.Column('source_system_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('extracted_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_pan', sa.String(length=20), nullable=True),
    sa.Column('extracted_gstin', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'external_id')
    )
    with op.batch_alter_table('source_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_record_extracted_gstin'), ['extracted_gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_record_extracted_pan'), ['extracted_pan'], unique=False)
        batch_op.create_index('ix_sr_name', ['extracted_name'], unique=False)

    op.create_table('status_snapshot',
    sa.Column('business_entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'dormant', 'closed', 'unknown', name='entitystatusenum', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_snapshot_business_entity_id'), ['business_entity_id'], unique=False)

    op.create_table('entity_record_link',
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('business_entity_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('auto_link', 'review', 'manual', 'rejected', name='linkdecisionenum', native_enum=False), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entity.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_record_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_record_link_business_entity_id'), ['business_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_record_link_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_record_link_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index('ix_link_confidence', ['confidence'], unique=False)

    op.create_table('review_case',
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'approved', 'rejected', 'closed', name='reviewcasestatusenum', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['business_entity.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_case_candidate_entity_id'), ['candidate_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_case_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_case_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_case_status'))
        batch_op.drop_index(batch_op.f('ix_review_case_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_review_case_candidate_entity_id'))

    op.drop_table('review_case')
    with op.batch_alter_table('entity_record_link', schema=None) as batch_op:
        batch_op.drop_index('ix_link_confidence')
        batch_op.drop_index(batch_op.f('ix_entity_record_link_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_entity_record_link_decision'))
        batch_op.drop_index(batch_op.f('ix_entity_record_link_business_entity_id'))

    op.drop_table('entity_record_link')
    with op.batch_alter_table('status_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_snapshot_business_entity_id'))

    op.drop_table('status_snapshot')
    with op.batch_alter_table('source_record', schema=None) as batch_op:
        batch_op.drop_index('ix_sr_name')
        batch_op.drop_index(batch_op.f('ix_source_record_extracted_pan'))
        batch_op.drop_index(batch_op.f('ix_source_record_extracted_gstin'))

    op.drop_table('source_record')
    with op.batch_alter_table('activity_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_activity_event_business_entity_id'))

    op.drop_table('activity_event')
    with op.batch_alter_table('source_system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_system_code'))

    op.drop_table('source_system')
    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_entity_ubid_code'))
        batch_op.drop_index(batch_op.f('ix_business_entity_status'))
        batch_op.drop_index(batch_op.f('ix_business_entity_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_business_entity_district'))

    op.drop_table('business_entity')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
