"""add address and pin_code to business and source_record

Revision ID: 901734de6b50
Revises: 6156a1bd5c0f
Create Date: 2026-09-04 16:39:52.467550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901734de6b50'
down_revision: Union[str, Sequence[str], None] = '6156a1bd5c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('normalized_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pin_code', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_business_entity_normalized_address'), ['normalized_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_entity_pin_code'), ['pin_code'], unique=False)

    with op.batch_alter_table('source_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('extracted_pin', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_source_record_extracted_pin'), ['extracted_pin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_record_extracted_pin'))
        batch_op.drop_column('extracted_pin')
        batch_op.drop_column('extracted_address')

    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_entity_pin_code'))
        batch_op.drop_index(batch_op.f('ix_business_entity_normalized_address'))
        batch_op.drop_column('pin_code')
        batch_op.drop_column('normalized_address')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
