"""add reviewer status lock to business_entity

Revision ID: ee4fd47dbd34
Revises: 901734de6b50
Create Date: 2026-09-04 17:05:04.292233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4fd47dbd34'
down_revision: Union[str, Sequence[str], None] = '901734de6b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status_locked', sa.Boolean(), nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(sa.Column('status_override_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status_overridden_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_entity', schema=None) as batch_op:
        batch_op.drop_column('status_overridden_by')
        batch_op.drop_column('status_override_reason')
        batch_op.drop_column('status_locked')

    # ### end Alembic commands ###
